### ISSUE TITLE
Failing reverse_reflection

### ISSUE THREAD

**Issue by iox** [Hobo/hobo#144]
https://groups.google.com/forum/#!searchin/hobousers/failing$20reverse_reflection/hobousers/V6aA87FUoeE/hbkg4OhiagAJ

**Comment by umuro** [comment]
There is an easy way to generate the problem.
Running functional tests always generates wrong DRYML(Class translations are not used, collection counts are missing)

**Comment by iox** [comment]
Hi @umuro ,

I have tried today to reproduce this error. I have set up an app with these relationships:

* parent.rb: `has_many :children, :foreign_key => :owner_id, :dependent => :destroy`
* child.rb: `belongs_to :owner, class_name: 'Parent'`

Then, in front/index.dryml:
```
<h3><%= Parent.reverse_reflection(:children).try :name %></h3>
<h3><%= Child.reverse_reflection(:owner).try :name %></h3>
```

In development mode, if I edit front/index.dryml and reload the page, the reverse reflections continue working as they should. Could you share a bit more info to help me reproduce?

In your previous comment, you have also mentioned that the Dryml functional tests create incorrect DRYML. Could you point me to the incorrect test? In our CI system, we run the command `bundle exec rake test:doctest` inside the Dryml folder. Is one of those tests?

Thanks a lot!

Warm regards,
Ignacio

**Comment by umuro** [comment]
It seems that Hobo is not to blame in this cause. I think the problem is because of my application. DRYML functional tests are OK. So I think we should close it as a Hobo issue.

It seems to be related to I18n.locale. In my application application controller sets I18n.locale in a before filter from current_user. This seems to effect DRYML generation. At least this explains  DRYML instability related to class names.

Is DRYML generation using I18n.default_locale or I18n.locale?

If it's using I18n.locale the problem and solution is clear, I think.

What is the entry point to DRYML generation in the rails app? If I make sure that there is never a locale change when entering DRYML generation then my problems should dissappear.

**Comment by iox** [comment]
The 3 dryml files in the auto folder are generated when the app starts. Also all taglibs are preloaded into memory before requests start coming. But the HTML is not generated until the render block. I'm not sure if I answered your question :P.
