### ISSUE TITLE
ArgumentError, wrong number of arguments (5 for 4)

### ISSUE THREAD

**Issue by mycaravam** [Hobo/hobo#178]
after a clean install and fixing sporckets to 2.1.1 this occurs when generating a new resource:
` end

      def find_templates(name, prefix, partial, details)
        tag_name = @controller.dryml_fallback_tag || name.dasherize + '-page'
        method_name = tag_name.to_s.gsub('-', '_')
        details[:virtual_path] = "#{prefix}/#{name}"`
any ideas?

**Comment by haslinger** [comment]
I can confirm this error.
I believe the reason is a [signature change of the find_templates method](https://github.com/rails/rails/compare/v4.2.5...v4.2.5.1#diff-40f2a5bcf9edfd65a8efe42a05c53736R183) in Rails 4.2.5.1 (compared to 4.2.5). 
The error always happens in [this line](https://github.com/Hobo/hobo/blob/master/dryml/lib/dryml/railtie/page_tag_resolver.rb#L10) of Hobo, where find_templates is overwritten with the old signature.

It I change this line (not really knowing, what I'm doing...) to
```def find_templates(name, prefix, partial, details, whatever)```
my tests would pass again, but I believe that way I would kill the security fix.

**Comment by tacid** [comment]
I can be wrong, but as I can see we can ignore this option, so just fix declaration of `find_templates` is just enough

**Comment by iox** [comment]
I think @tacid 's solution is good enough, and maintains the security fix. Thanks!

**Comment by haslinger** [comment]
@tacid @iox Thanks for your work! I got all my app's instances running on 4.2.5 literally today morning, and I almost thought I could take next week off. Seems I've some work next week upgrading again :-)

**Comment by iox** [comment]
Updates are a never ending story :D.

By the way, I just fixed all the tests in the master branch with Rails 4.2.5.1, everything is green again.

**Comment by haslinger** [comment]
@iox it would be great, if you could bump up the Hobo version and push to Rubygems. Upgrade would be easier and fresh installs would work again.

**Comment by iox** [comment]
Of course, it's in my task list.
